#! /bin/sh

. /home/jeff/Projects/py2.7/bin/activate
export CHECKMATE_HOME=/home/jeff/Projects/bitbucket/checkmate
export PYTHONPATH=$CHECKMATE_HOME
export PYTHONUSERBASE=$PYTHONPATH
export MYSQL_USER='root'
export MYSQL_PASSWORD=$MYSQL_PASSWORD
export MYSQL_HOST='localhost'
export TANGO_INSTALL_DIR=/opt/installation/kgs-tango-8.1.2
export PATH=$TANGO_INSTALL_DIR/bin:$PATH
export BOOST_ROOT=/opt/installation/boost_1_54_0_py2.7
export OMNI_ROOT=/opt/omniORB-4.1.6
export TANGO_ROOT=$TANGO_INSTALL_DIR
export LD_LIBRARY_PATH=$TANGO_INSTALL_DIR/lib:/usr/local/mysql/lib:$OMNI_ROOT/lib:$BOOST_ROOT/lib:$LD_LIBRARY_PATH
export TANGO_DB_NAME=checkmate
export TANGO_HOST='localhost:10000'

python ./pytango/component/component_2_taurus.py
trap "pkill -f \"python ./pytango/component/component_2_taurus.py\"" 1 2 3 15
