/*----- PROTECTED REGION ID(Component_3StateMachine.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        Component_3StateMachine.cpp
//
// description : State machine file for the Component_3 class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include <Component_3.h>

/*----- PROTECTED REGION END -----*/	//	Component_3::Component_3StateMachine.cpp

//================================================================
//  States  |  Description
//================================================================


namespace Component_3_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method      : Component_3::is_toggle_allowed()
 *	Description : Execution allowed for toggle attribute
 */
//--------------------------------------------------------
bool Component_3::is_toggle_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for toggle command.
	/*----- PROTECTED REGION ID(Component_3::toggleStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Component_3::toggleStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Component_3::is_RE_allowed()
 *	Description : Execution allowed for RE attribute
 */
//--------------------------------------------------------
bool Component_3::is_RE_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for RE command.
	/*----- PROTECTED REGION ID(Component_3::REStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Component_3::REStateAllowed
	return true;
}

//--------------------------------------------------------
/**
 *	Method      : Component_3::is_RL_allowed()
 *	Description : Execution allowed for RL attribute
 */
//--------------------------------------------------------
bool Component_3::is_RL_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for RL command.
	/*----- PROTECTED REGION ID(Component_3::RLStateAllowed) ENABLED START -----*/
	
	/*----- PROTECTED REGION END -----*/	//	Component_3::RLStateAllowed
	return true;
}

}	//	End of namespace
