#! /bin/sh

#move all the environment variables to py2.7 bin/activate
. $PY2_VIRTUAL_ENV/bin/activate

python ./pytango/component/component_2_taurus.py &
#15 means SIGTERM
while ((true))
do
trap "kill $!" 15
done
